### ISSUE TITLE
N/A

### ISSUE THREAD

**Issue by Segeco** [gormanb/homebridge-hivehome-control#2]
N/A

**Comment by Segeco** [comment]
N/A

**Comment by gormanb** [comment]
Hi @Segeco! The error you're seeing when installing the plugin is due to recent versions of Python adopting [PEP668](https://peps.python.org/pep-0668/), which basically states that `pip` cannot globally install python packages into an environment that is being managed by the system. As mentioned [in the README](https://github.com/gormanb/homebridge-hivehome-control?tab=readme-ov-file#requirements), this plugin requires `python3` and `pip3` so that it can install some python dependencies.

To address this, I've just published a beta version `1.0.3-beta.1`, which manages its python packages internally and should therefore avoid hitting this error. Please try installing that version and let me know if it works for you.

You can also try running the 2FA setup script with the new beta version as follows:
```
npx homebridge-hivehome-control@1.0.3-beta.1
```
The error you saw previously, `Unexpected token import`, seems to be because you're running v8.9.0 of `node`, which [does not support the `import <package>` syntax](https://stackoverflow.com/questions/39436322/node-js-syntaxerror-unexpected-token-import). Since this is quite an old version and is no longer maintained, I'd recommend upgrading to a more recent stable version of Node and trying again.

**Comment by gormanb** [comment]
Hi @Segeco, did you manage to solve the problem?

**Comment by gormanb** [comment]
@Segeco: I've promoted the beta to a full v1.0.3 release. Let me know if installing this version resolved the exception you were hitting.

**Comment by gormanb** [comment]
Closing out this issue - if you're still having problems, please feel free to reopen it or file a new report!
